const Map<String, List<Map<String, dynamic>>> insumos = {
  "BALDES": [
    {"nome": "BAUNILHA, PAÇOCA E DOCE DE LEITE", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BEM CASADO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "FLOCOS DA AMAZÔNIA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "COCADA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "DOCE DE LEITE ORAMA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CAFÉ DA MANTIQUEIRA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "PAÇOCA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BANANA CARAMELADA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MENTA COM CHOCOLATE", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BOLO DE CENOURA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CACAU BAHIA COM LARANJA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BRIGADEIRO MEIO AMARGO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "REQUEIJÃO COM GOIABADA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MILHO VERDE", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MOUSSE DE MARACUJÁ COM BOLO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "COCO COM ABÓBORA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MARACUJÁ E MEL", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MANGA COM ALECRIM", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MORANGO COM HORTELÃ", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "LIMÃO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CUPUAÇU", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "AMORA DO CAXAMBU", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "UVA VITÓRIA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "UVA NIÁGARA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "TAMARINDO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MURICI", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CAMBUCI", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "SIRIGUELA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CAJÁ", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "AÇAÍ DA AMAZÔNIA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BRIGADEIRO COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BANANA COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CARAMELO COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "AÇAÍ VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "PITAYA COM MORANGO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CHOCOLATE VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "UVA VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "LIMÃO COM CAPIM SANTO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "COCO VERDE VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"}
  ],
  "CUBAS": [
    {"nome": "BAUNILHA, PAÇOCA E DOCE DE LEITE", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BAUNILHA COM MORANGO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BEM CASADO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "FLOCOS DA AMAZÔNIA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "COCADA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "DOCE DE LEITE ORAMA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CAFÉ DA MANTIQUEIRA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "PAÇOCA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BANANA CARAMELADA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MENTA COM CHOCOLATE", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BOLO DE CENOURA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CACAU BAHIA COM LARANJA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BRIGADEIRO MEIO AMARGO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "REQUEIJÃO COM GOIABADA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MILHO VERDE", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MOUSSE DE MARACUJÁ COM BOLO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "COCO COM ABÓBORA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MARACUJÁ E MEL", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MANGA COM ALECRIM", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MORANGO COM HORTELÃ", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "LIMÃO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CUPUAÇU", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "AMORA DO CAXAMBU", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "UVA VITÓRIA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "UVA NIÁGARA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "TAMARINDO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "MURICI", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CAMBUCI", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "SIRIGUELA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CAJÁ", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "AÇAÍ DA AMAZÔNIA", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BRIGADEIRO COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "BANANA COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CARAMELO COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "AÇAÍ VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "PITAYA COM MORANGO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "CHOCOLATE VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "UVA VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "LIMÃO COM CAPIM SANTO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"},
    {"nome": "COCO VERDE VEGANO ZERO", "estoque_id": "E1A", "tipo": "Balde", "nomeclatura": "PPC"}
  ],
  "POTES": [
    {"nome": "BAUNILHA, PAÇOCA E DOCE DE LEITE", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "BEM CASADO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "FLOCOS DA AMAZÔNIA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "COCADA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "DOCE DE LEITE ORAMA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CAFÉ DA MANTIQUEIRA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "PAÇOCA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "BANANA CARAMELADA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MENTA COM CHOCOLATE", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "BOLO DE CENOURA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CACAU BAHIA COM LARANJA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "BRIGADEIRO MEIO AMARGO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "REQUEIJÃO COM GOIABADA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MILHO VERDE", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MOUSSE DE MARACUJÁ COM BOLO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "COCO COM ABÓBORA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MARACUJÁ E MEL", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MANGA COM ALECRIM", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MORANGO COM HORTELÃ", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "LIMÃO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CUPUAÇU", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "AMORA DO CAXAMBU", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "UVA VITÓRIA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "UVA NIÁGARA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "TAMARINDO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "MURICI", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CAMBUCI", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "SIRIGUELA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CAJÁ", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "AÇAÍ DA AMAZÔNIA", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "BRIGADEIRO COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "BANANA COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CARAMELO COM WHEY ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "AÇAÍ VEGANO ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "PITAYA COM MORANGO ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "CHOCOLATE VEGANO ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "UVA VEGANO ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "LIMÃO COM CAPIM SANTO ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"},
    {"nome": "COCO VERDE VEGANO ZERO", "estoque_id": "E1A", "tipo": "Pote", "nomeclatura": "PPC"}
  ],
  "COOKIES": [
    {"nome": "TRAD. BAUNILHA AO LEITE - BAUNILHA + CHOC. AO LEITE", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "BAUNILHA BRANCO - BAUNILHA + CHOCOLATE BRANCO", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "BANANA - CHOC LEITE + BANANA", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "BAUNILHA COM CAFÉ - BAUNILHA + CAFÉ + CHOC. AO LEITE ", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "DUPLO CHOCOLATE - CHOCOLATE 70% + CHOCOLATE 50%", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "BROWNIE - CHOCOLATE 50% + CASTANHAS DE CAJU", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "CHOCOLATE AO LEITE - CHOCOLATE + CHOC. AO LEITE", "estoque_id": "E1A","nomeclatura": "PPC", "tipo": "Un"}
  ],
  "PÃO DE QUEIJO": [
    {"nome": "PAO DE QUEIJO GRANDE 90 GRAMAS", "estoque_id": "E1A", "nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "PAO DE QUEIJO MINI 20 GRAMAS", "estoque_id": "E1A", "nomeclatura": "PPC", "tipo": "Un"}
  ],
  "SECOS": [
    {"nome": "BOLACHINHA BAUNILHA", "estoque_id": "E2A", "nomeclatura": "PPS", "tipo": "Un"},
    {"nome": "BOLACHINHA CANELA", "estoque_id": "E2A", "nomeclatura": "PPS", "tipo": "Un"},
    {"nome": "BOLACHINHA CHOCOLATE", "estoque_id": "E2A", "nomeclatura": "PPS", "tipo": "Un"},
    {"nome": "CONE VIAGEM BAUNILHA", "estoque_id": "E2A", "nomeclatura": "PPS", "tipo": "Un"},
    {"nome": "CONE VIAGEM CANELA", "estoque_id": "E2A", "nomeclatura": "PPS", "tipo": "Un"},
    {"nome": "CONE VIAGEM CHOCOLATE", "estoque_id": "E2A", "nomeclatura": "PPS", "tipo": "Un"}
  ],
  "TOPPINGS": [
    {"nome": "MASSA BOLO DE COCO", "estoque_id": "E1A", "nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "CASTANHA GLACEADAS P/ TOPPING", "estoque_id": "E1C", "nomeclatura": "PPS", "tipo": "g"},
    {"nome": "DOCE DE BANANA P/TOPPING", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"},
    {"nome": "DOCE DE GOIABA P/TOPPING", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"},
    {"nome": "CALDA DE BRIGADEIRO P/ TOPPING", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"},
    {"nome": "GANACHE DE LEITE", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"},
    {"nome": "GANACHE MEIO AMARGA", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"},
    {"nome": "MASSA BAUNILHA CASQUINHA", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Tubo"},
    {"nome": "MASSA BOLO CENOURA", "estoque_id": "E1A", "nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "MASSA BOLO CHOCOLATE", "estoque_id": "E1A", "nomeclatura": "PPC", "tipo": "Un"},
    {"nome": "MASSA CANELA CASQUINHAS", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Tubo"},
    {"nome": "RASPAS DE LARANJA P/TOPPING", "estoque_id": "E1C", "nomeclatura": "PPS", "tipo": "g"},
    {"nome": "CALDA DE DOCE DE LEITE P/TOPPING", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"},
    {"nome": "CALDA DE FRUTAS DE MORANGO P/TOPPING", "estoque_id": "E1B", "nomeclatura": "PPR", "tipo": "Un"}
  ],
  "PERECÍVEIS": [
  {"nome": "CEBOLA ROXA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Un"},
  {"nome": "CEBOLINHA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "MORANGO", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "RÚCULA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "MELADO", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "SALSINHA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "UVA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "TOMATINHO", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "g"},
  {"nome": "BANANA DA TERRA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Un"},
  {"nome": "BANANA PRATA", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Un"},
  {"nome": "PEITO DE PERU/LOMBO", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Un"},
  {"nome": "PEPPERONI", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Un"},
  {"nome": "PIMENTA BIQUINHO", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Pote"},
  {"nome": "QUEIJO COALHO", "estoque_id": "-", "nomeclatura": "PTR", "tipo": "Un"},
  {"nome": "QUEIJO MINAS FRESCAL", "estoque_id": "E1B", "nomeclatura": "PTR", 'tipo': 'Un'},
],
  "POLPAS": [
  {"nome": "ABACAXI", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "AMORA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "CACAU", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "CAJÁ", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "CAMBUCI", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "CUPUAÇU", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "FRUTAS VERMELHAS", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "GRAVIOLA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "JENIPAPO", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "LIMÃO", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "MANGA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "MARACUJÁ", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "MORANGO POLPA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "MURICI", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "PITAYA VERMELHA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "SIRIGUELA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "TAMARINDO", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "UMBÚ", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "UVA POLPA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"},
  {"nome": "UVAIA", "estoque_id": "E1A", "nomeclatura": "PTC", "tipo": "Un"}
],
  "INSUMOS": [
    {"nome": "CARNE SECA", "estoque_id": "E1A", "nomeclatura": "PPC", 'tipo': 'Un'},
    {"nome": "CREME DE TOMATE SECO", "estoque_id": "E1C", "nomeclatura": "PTS", 'tipo': 'g'},
    {"nome": "FRANGO DESFIADO", "estoque_id": "E1A", "nomeclatura": "PPC", 'tipo': 'Un'},
    {"nome": "MARGARINA", "estoque_id": "E1B", "nomeclatura": "PTR", 'tipo': 'g'},
    {"nome": "MASSA DE TAPIOCA", "estoque_id": "E1A", "nomeclatura": "PTC", 'tipo': 'Kg'},
    {"nome": "MOSTARDA DIJON", "estoque_id": "E1C", "nomeclatura": "PTS", 'tipo': 'g'},
    {"nome": "PASTA DE BERINJELA", "estoque_id": "E1C", "nomeclatura": "PTS", 'tipo': 'g'},
    {"nome": "COCO FRESCO", "estoque_id": "E1A", "nomeclatura": "PTC", 'tipo': 'g'},
    {"nome": "AMENDOAS", "estoque_id": "E1C", "nomeclatura": "PPS", 'tipo': '-'},
    {"nome": "PERNIL", "estoque_id": "E1A", "nomeclatura": "PPC", 'tipo': 'Un'},
    {"nome": "PESTO DE MANJERICÃO", "estoque_id": "E1B", "nomeclatura": "PTS", "tipo": "g"},
    {"nome": "QUEIJO MINAS", "estoque_id": "E1A", "nomeclatura": "PPC", 'tipo': 'Un'},
    {"nome": "QUEIJO MUSSARELA", "estoque_id": "E1A", "nomeclatura": "PPC", 'tipo': 'Un'}
  ],
  "MESCLAS": [
    {"nome": "DOCE DE LEITE PASTOSO",  "estoque_id": "-", "nomeclatura": "PTS", 'tipo': '-'},
    {"nome": "CHOCOLATE P/ FLOCOS",  "estoque_id": "-", "nomeclatura": "PTR", 'tipo': '-'},
    {"nome": "CHOCOLATE BRANCO",  "estoque_id": "-", "nomeclatura": "PTR", 'tipo': '-'},
    {"nome": "CREME DE CAJU C/ CHOCOLATE",  "estoque_id": "-", "nomeclatura": "PTR", 'tipo': '-'}
  ],
  'ÁGUA': [
    {"nome": "ÁGUA COM GÁS",  "estoque_id": "-", "nomeclatura": "PTS", 'tipo': 'Fardo'},
    {"nome": "ÁGUA SEM GÁS",  "estoque_id": "-", "nomeclatura": "PTS", 'tipo': 'Fardo'},
  ],
  'DESCARTÁVEIS': [
    {"nome": "KRAFT PÃO DE QUEIJO/COOKIES VIAGEM", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "AÇÚCAR SACHE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "ADOÇANTE SACHE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "BARBANTE (UNIDADE)", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': '-'},
    {"nome": "ISOPOR (PROMOÇÃO)", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CANUDO SACODE/SUCO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "COLHER DE PLÁSTICO VIAGEM", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "COPO PLÁSTICO 450ML", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "GUARDANAPO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "INTERFOLHA DE PAREDE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "LUVAS", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "PA DE MADEIRA AMOSTRA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "PA DE MADEIRA GRANDE P/ SERVIR", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "PALITO MEXEDOR DE CAFÉ", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Caixa'},
    {"nome": "POTE SORVETE ORAMA 120ML", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Sacos'},
    {"nome": "POTE SORVETE VIAGEM 500ML", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Sacos'},
    {"nome": "ROLO FILME", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "SACOLA PARDA PAPEL ORAMA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "TAMPA SACODE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "TOUCAS DESCARTÁVEIS", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "BOBINA MÁQUINA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "BOBINA CUPOM FISCAL", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "PAPEL HIGIENICO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'}
  ],
  'LIMPEZA': [
    {"nome": "ALCOOL 70%", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Litro'},
    {"nome": "ALCOOL GEL CLIENTE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Litro'},
    {"nome": "CLORO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Litro'},
    {"nome": "DETERGENTE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Litro'},
    {"nome": "ESPONJA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "MOPP", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "PANOS BRANCOS", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "PERFEX", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Rolo'},
    {"nome": "RODO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "SABONETE INCOLOR P/ MÃOS", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "SACO DE LIXO 100L PRETO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "SACO DE LIXO 30L PRETO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "VASSOURA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "VEJA LIMPA VIDRO TRANSPARENTE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "VEJA MULTIUSO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "DESINFETANTE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Litro'}
  ],
  'UNIFORMES': [
    {"nome": "AVENTAL JEANS", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CAMISETA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "ETIQUETA VALIDADE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "TOUCA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'}
  ],
  'UTENSÍLIOS': [
    {"nome": "BALDE DE ÁGUA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "BOLEADOR AÇO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CAIXA SOM JBL", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "COLHER DE METAL", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CUBAS DE AÇO SORVETE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CUMBUCA DE PORCELANA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "ESPATULA AÇO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "ESPÁTULA BORRACHA (MANTEIGA)", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "ESTUFA DE CASQUINHAS", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "FACA DE SERRA PÃO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "GRILL DE PÃO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "LIQUIDIFICADOR", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "MÁQUINA DE CASQUINHA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "MIXER MILK SHAKE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "MOLDE DE CASQUINHA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "PEGADOR CASQUINHA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "PIRES GRANDE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "PIRES PEQUENO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "POTE AÇAÍ GRANDE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "XÍCARA CAFÉ GRANDE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "XÍCARA CAFÉ PEQUENA", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CRONÔMETRO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "MÁQUINA DE CAFÉ", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "MOEDOR DE CAFÉ", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'}
  ],
  'PAPELARIA': [
    {"nome": "CANETA BIC", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "CANETA PERMANENTE", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "FITA DUREX", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'},
    {"nome": "GRAMPO", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': '-'},
    {"nome": "POST-IT", "estoque_id": "E2B", "nomeclatura": "PTS", 'tipo': 'Un'}
  ]
};